version: '3'

services:
  sirous_postgresql:
    image: postgres:13
    container_name: sirous_postgresql
    volumes:
      - sirous_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - sirous_network
volumes:
  sirous_postgresql:
    external: true
networks:
  sirous_network:
    external: true