# Generated by Django 3.2.4 on 2021-06-13 18:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_item', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ModelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_item', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StatusItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_item', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=512)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('price_ir', models.IntegerField()),
                ('price_usd', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('date_in', models.DateTimeField(default=datetime.datetime.now)),
                ('brand_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.branditem')),
                ('model_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.modelitem')),
                ('status_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.statusitem')),
            ],
        ),
    ]
