# Generated by Django 3.2.4 on 2021-06-13 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20210613_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anyitem',
            name='status_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='items.statusitem'),
        ),
    ]
